package main

import (
	"bufio"
	"crypto/tls"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	mqtt "github.com/eclipse/paho.mqtt.golang"
	"gopkg.in/natefinch/lumberjack.v2"
)

// =====================
// Config
// =====================

type Config struct {
	// SIA
	SIAListenAddr string // e.g. ":45128"
	SIAAccountID  string // e.g. "AAAA" - for verification

	// HTTP stats
	HTTPListenAddr string // e.g. "127.0.0.1:8080"

	// Persisted state
	StateFile string

	// MQTT
	MQTTBroker   string
	MQTTUser     string
	MQTTPass     string
	MQTTClientID string // if empty, autogenerated
	MQTTTopic    string // state topic (JSON)
	MQTTQOS      byte   // 0..2
	MQTTRetain   bool   // retain state JSON

	// Online/offline
	MQTTAvailabilityTopic string
	MQTTAvailabilityOn    string
	MQTTAvailabilityOff   string

	// MQTT Discovery (single sensor)
	MQTTDiscoveryEnable bool
	MQTTDiscoveryPrefix string // usually "homeassistant"
	MQTTDiscoveryNodeID string // e.g. "ajax"
	MQTTDiscoveryObject string // e.g. "alarm_state"
	MQTTDiscoveryName   string // e.g. "Ajax Alarm State"

	// TLS
	MQTTInsecureSkipVerify bool

	// Logging
	LogFile       string
	LogMaxSizeMB  int
	LogMaxBackups int
	LogMaxAgeDays int
	Verbose       bool
}

func defaultConfig() Config {
	return Config{
		SIAListenAddr:  ":45128",
		SIAAccountID:   "",
		HTTPListenAddr: "127.0.0.1:8080",
		StateFile:      "/var/lib/sia2mqtt/state.json",

		MQTTBroker:   "tcp://127.0.0.1:1883",
		MQTTUser:     "",
		MQTTPass:     "",
		MQTTClientID: "",

		MQTTTopic:  "home/alarm/ajax/state",
		MQTTQOS:    0,
		MQTTRetain: true,

		MQTTAvailabilityTopic: "home/alarm/ajax/availability",
		MQTTAvailabilityOn:    "online",
		MQTTAvailabilityOff:   "offline",

		MQTTDiscoveryEnable: true,
		MQTTDiscoveryPrefix: "homeassistant",
		MQTTDiscoveryNodeID: "ajax",
		MQTTDiscoveryObject: "alarm_state",
		MQTTDiscoveryName:   "Ajax Alarm State",

		MQTTInsecureSkipVerify: false,

		LogFile:       "/var/log/sia2mqtt/sia2mqtt.log",
		LogMaxSizeMB:  10,
		LogMaxBackups: 5,
		LogMaxAgeDays: 30,
		Verbose:       false,
	}
}

const DefaultConfigPath = "/etc/sia2mqtt.conf"

func loadConfig(path string) (Config, error) {
	cfg := defaultConfig()

	f, err := os.Open(path)
	if err != nil {
		return cfg, err
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	lineno := 0
	for sc.Scan() {
		lineno++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			return cfg, fmt.Errorf("%s:%d invalid line (expected key=value): %q", path, lineno, line)
		}
		key := strings.ToLower(strings.TrimSpace(k))
		val := strings.TrimSpace(v)

		switch key {
		case "sia_listen":
			cfg.SIAListenAddr = val
		case "sia_account_id":
			cfg.SIAAccountID = val
		case "http_listen":
			cfg.HTTPListenAddr = val
		case "state_file":
			cfg.StateFile = val

		case "mqtt_broker":
			cfg.MQTTBroker = val
		case "mqtt_user":
			cfg.MQTTUser = val
		case "mqtt_password":
			cfg.MQTTPass = val
		case "mqtt_clientid":
			cfg.MQTTClientID = val
		case "mqtt_topic":
			cfg.MQTTTopic = val
		case "mqtt_qos":
			n, e := strconv.Atoi(val)
			if e != nil || n < 0 || n > 2 {
				return cfg, fmt.Errorf("%s:%d mqtt_qos must be 0..2: %q", path, lineno, val)
			}
			cfg.MQTTQOS = byte(n)
		case "mqtt_retain":
			b, e := parseBool(val)
			if e != nil {
				return cfg, fmt.Errorf("%s:%d mqtt_retain invalid: %q", path, lineno, val)
			}
			cfg.MQTTRetain = b

		case "mqtt_availability_topic":
			cfg.MQTTAvailabilityTopic = val
		case "mqtt_availability_online":
			cfg.MQTTAvailabilityOn = val
		case "mqtt_availability_offline":
			cfg.MQTTAvailabilityOff = val

		case "mqtt_discovery_enable":
			b, e := parseBool(val)
			if e != nil {
				return cfg, fmt.Errorf("%s:%d mqtt_discovery_enable invalid: %q", path, lineno, val)
			}
			cfg.MQTTDiscoveryEnable = b
		case "mqtt_discovery_prefix":
			cfg.MQTTDiscoveryPrefix = val
		case "mqtt_discovery_node_id":
			cfg.MQTTDiscoveryNodeID = val
		case "mqtt_discovery_object_id":
			cfg.MQTTDiscoveryObject = val
		case "mqtt_discovery_name":
			cfg.MQTTDiscoveryName = val

		case "mqtt_tls_insecure_skip_verify":
			b, e := parseBool(val)
			if e != nil {
				return cfg, fmt.Errorf("%s:%d mqtt_tls_insecure_skip_verify invalid: %q", path, lineno, val)
			}
			cfg.MQTTInsecureSkipVerify = b

		case "log_file":
			cfg.LogFile = val
		case "log_max_size_mb":
			n, e := strconv.Atoi(val)
			if e != nil || n <= 0 {
				return cfg, fmt.Errorf("%s:%d log_max_size_mb must be positive: %q", path, lineno, val)
			}
			cfg.LogMaxSizeMB = n
		case "log_max_backups":
			n, e := strconv.Atoi(val)
			if e != nil || n < 0 {
				return cfg, fmt.Errorf("%s:%d log_max_backups must be non-negative: %q", path, lineno, val)
			}
			cfg.LogMaxBackups = n
		case "log_max_age_days":
			n, e := strconv.Atoi(val)
			if e != nil || n < 0 {
				return cfg, fmt.Errorf("%s:%d log_max_age_days must be non-negative: %q", path, lineno, val)
			}
			cfg.LogMaxAgeDays = n

		case "verbose":
			b, e := parseBool(val)
			if e != nil {
				return cfg, fmt.Errorf("%s:%d verbose invalid: %q", path, lineno, val)
			}
			cfg.Verbose = b

		default:
			return cfg, fmt.Errorf("%s:%d unknown key: %q", path, lineno, key)
		}
	}
	if err := sc.Err(); err != nil {
		return cfg, err
	}

	if cfg.MQTTBroker == "" {
		return cfg, errors.New("mqtt_broker is required")
	}
	if cfg.MQTTTopic == "" {
		return cfg, errors.New("mqtt_topic is required")
	}
	if cfg.SIAListenAddr == "" {
		return cfg, errors.New("sia_listen is required")
	}
	if cfg.HTTPListenAddr == "" {
		return cfg, errors.New("http_listen is required")
	}
	if cfg.MQTTDiscoveryPrefix == "" {
		cfg.MQTTDiscoveryPrefix = "homeassistant"
	}
	if cfg.MQTTDiscoveryNodeID == "" {
		cfg.MQTTDiscoveryNodeID = "ajax"
	}
	if cfg.MQTTDiscoveryObject == "" {
		cfg.MQTTDiscoveryObject = "alarm_state"
	}
	if cfg.MQTTDiscoveryName == "" {
		cfg.MQTTDiscoveryName = "Ajax Alarm State"
	}
	return cfg, nil
}

func parseBool(s string) (bool, error) {
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "1", "true", "yes", "on":
		return true, nil
	case "0", "false", "no", "off":
		return false, nil
	default:
		return false, fmt.Errorf("invalid bool: %q", s)
	}
}

// =====================
// SIA / Ajax
// =====================

// Ajax hubs use CRC-16/IBM (aka ARC): poly 0xA001, init 0x0000.
func calcCRC(data []byte) string {
	var crc uint16 = 0x0000
	for _, b := range data {
		crc ^= uint16(b)
		for i := 0; i < 8; i++ {
			if (crc & 0x0001) != 0 {
				crc = (crc >> 1) ^ 0xA001
			} else {
				crc >>= 1
			}
		}
	}
	return fmt.Sprintf("%04X", crc)
}

func fmtLEN(n int) string { return fmt.Sprintf("%04X", n) }

const maxFrameSize = 16 * 1024

func readFrame(r *bufio.Reader) ([]byte, error) {
	for {
		b, err := r.ReadByte()
		if err != nil {
			return nil, err
		}
		if b != '\r' && b != '\n' {
			_ = r.UnreadByte()
			break
		}
	}
	var buf []byte
	for {
		b, err := r.ReadByte()
		if err != nil {
			if err == io.EOF && len(buf) > 0 {
				return buf, nil
			}
			return nil, err
		}
		if b == '\r' || b == '\n' {
			return buf, nil
		}
		buf = append(buf, b)
		if len(buf) > maxFrameSize {
			return nil, fmt.Errorf("frame exceeds maximum size (%d bytes)", maxFrameSize)
		}
	}
}

func buildAck(seq, rcvrOpt, lpref, acct string) []byte {
	payload := fmt.Sprintf("\"ACK\"%s%s%s#%s[]", seq, rcvrOpt, lpref, acct)
	l := fmtLEN(len(payload))
	crc := calcCRC([]byte(payload))
	return []byte("\n" + crc + l + payload + "\r")
}

// Updated regex to capture event code and user ID separately
var reEventCode = regexp.MustCompile(`\|[^/]+/([A-Z]{2})([0-9]{3})?`)
var reHeader = regexp.MustCompile(`^[0-9A-F]{4}[0-9A-F]{4}"(?:\*?SIA-DCS|\*?ADM-CID|NULL)"([0-9]{4})(R[0-9A-F]{1,6})?(L[0-9A-F]{1,6})#([0-9A-F]{3,16})`)

type AlarmState string

const (
	StateUnknown  AlarmState = "unknown"
	StateDisarmed AlarmState = "disarmed"
	StateArmed    AlarmState = "armed"
	StateNight    AlarmState = "night"
	StateAlarm    AlarmState = "alarm"
)

// Map event codes (2 letters only) to states - works for ANY user ID
var codeToState = map[string]AlarmState{
	// Disarmed codes
	"OP": StateDisarmed, // Opening Report
	"OA": StateDisarmed, // Automatic Opening
	"OQ": StateDisarmed, // Remote Opening
	"OG": StateDisarmed, // Open Area (partial disarm)
	"OR": StateDisarmed, // Disarm From Alarm

	// Armed codes
	"CL": StateArmed, // Closing Report
	"CA": StateArmed, // Automatic Closing
	"CP": StateArmed, // Automatic Closing
	"CQ": StateArmed, // Remote Closing
	"CF": StateArmed, // Forced Closing

	// Night/Perimeter armed codes
	"NL": StateNight, // Perimeter Armed
	"NM": StateNight, // Perimeter Armed, User Defined
	"NF": StateNight, // Forced Perimeter Arm

	// Alarm codes
	"BA": StateAlarm, // Burglary Alarm
	"TA": StateAlarm, // Tamper Alarm
	"FA": StateAlarm, // Fire Alarm
	"PA": StateAlarm, // Panic Alarm
	"HA": StateAlarm, // Holdup Alarm
	"MA": StateAlarm, // Medical Alarm
	"BV": StateAlarm, // Burglary Verified
	"GA": StateAlarm, // Gas Alarm
	"WA": StateAlarm, // Water Alarm
	"KA": StateAlarm, // Heat Alarm
}

// =====================
// Runtime stats
// =====================

type RuntimeStats struct {
	StartTime time.Time

	ActiveConn int64 // atomic

	FramesRx                uint64 // atomic
	AcksTx                  uint64 // atomic
	MQTTPubOK               uint64 // atomic
	MQTTPubErr              uint64 // atomic
	RejectedAccountMismatch uint64 // atomic

	mu                  sync.RWMutex
	LastState           AlarmState
	LastCode            string
	LastUser            string
	LastEventRaw        string
	LastEventTime       time.Time
	LastMQTTPublishTime time.Time
}

type PersistedState struct {
	State         AlarmState `json:"state"`
	Code          string     `json:"code"`
	User          string     `json:"user"`
	LastEventTime time.Time  `json:"last_event_time"`
}

func (s *RuntimeStats) UpdateEvent(state AlarmState, code, user, raw string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.LastState = state
	s.LastCode = code
	s.LastUser = user
	s.LastEventRaw = raw
	s.LastEventTime = time.Now()
}

func (s *RuntimeStats) Snapshot() PersistedState {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return PersistedState{
		State:         s.LastState,
		Code:          s.LastCode,
		User:          s.LastUser,
		LastEventTime: s.LastEventTime,
	}
}

func (s *RuntimeStats) ApplyPersistedState(p PersistedState) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if p.State != "" {
		s.LastState = p.State
	}
	if p.Code != "" {
		s.LastCode = p.Code
	}
	if p.User != "" {
		s.LastUser = p.User
	}
	if !p.LastEventTime.IsZero() {
		s.LastEventTime = p.LastEventTime
	}
}

func (s *RuntimeStats) UpdateMQTTPublish(ok bool) {
	if ok {
		atomic.AddUint64(&s.MQTTPubOK, 1)
	} else {
		atomic.AddUint64(&s.MQTTPubErr, 1)
	}
	s.mu.Lock()
	s.LastMQTTPublishTime = time.Now()
	s.mu.Unlock()
}

// =====================
// MQTT + Discovery
// =====================

type Publisher struct {
	cfg   Config
	stats *RuntimeStats

	client mqtt.Client

	mu        sync.Mutex
	lastState AlarmState
	lastCode  string
	lastUser  string

	// ensure we only publish discovery config once per process start
	discoverySent atomic.Bool
}

func (p *Publisher) discoveryConfigTopic() string {
	// homeassistant/sensor/<node_id>/<object_id>/config
	return fmt.Sprintf("%s/sensor/%s/%s/config",
		strings.TrimSuffix(p.cfg.MQTTDiscoveryPrefix, "/"),
		p.cfg.MQTTDiscoveryNodeID,
		p.cfg.MQTTDiscoveryObject,
	)
}

func (p *Publisher) userDiscoveryConfigTopic() string {
	// homeassistant/sensor/<node_id>/user/config
	return fmt.Sprintf("%s/sensor/%s/user/config",
		strings.TrimSuffix(p.cfg.MQTTDiscoveryPrefix, "/"),
		p.cfg.MQTTDiscoveryNodeID,
	)
}

func (p *Publisher) uniqueID() string {
	return fmt.Sprintf("%s_%s", p.cfg.MQTTDiscoveryNodeID, p.cfg.MQTTDiscoveryObject)
}

func (p *Publisher) userTopic() string {
	// home/alarm/ajax/user
	return strings.TrimSuffix(p.cfg.MQTTTopic, "/state") + "/user"
}

func (p *Publisher) publishDiscoveryConfig() {
	if !p.cfg.MQTTDiscoveryEnable {
		return
	}
	if p.discoverySent.Load() {
		return
	}
	if p.client == nil || !p.client.IsConnected() {
		return
	}

	// 1. Publish STATE sensor discovery
	statePayload := map[string]any{
		"name":                  p.cfg.MQTTDiscoveryName,
		"unique_id":             p.uniqueID(),
		"state_topic":           p.cfg.MQTTTopic,
		"availability_topic":    p.cfg.MQTTAvailabilityTopic,
		"payload_available":     p.cfg.MQTTAvailabilityOn,
		"payload_not_available": p.cfg.MQTTAvailabilityOff,
		"value_template":        `{{ value_json.state }}`,
		"device_class":          "enum",
		"options":               []string{string(StateUnknown), string(StateDisarmed), string(StateArmed), string(StateNight), string(StateAlarm)},
		"icon":                  "mdi:shield-home",

		"device": map[string]any{
			"identifiers":  []string{"sia2mqtt_ajax"},
			"name":         "sia2mqtt Ajax",
			"manufacturer": "Custom",
			"model":        "SIA DC-09 Receiver",
		},
	}

	stateBody, _ := json.Marshal(statePayload)
	stateTopic := p.discoveryConfigTopic()
	t1 := p.client.Publish(stateTopic, p.cfg.MQTTQOS, true, stateBody)
	t1.Wait()
	if t1.Error() == nil {
		log.Printf("[%s] MQTT discovery (state) published: %s\n", time.Now().Format("15:04:05"), stateTopic)
	} else {
		log.Printf("[%s] MQTT discovery (state) publish error: %v\n", time.Now().Format("15:04:05"), t1.Error())
		return
	}

	// 2. Publish USER sensor discovery
	userPayload := map[string]any{
		"name":                  p.cfg.MQTTDiscoveryName + " Last User",
		"unique_id":             p.uniqueID() + "_user",
		"state_topic":           p.userTopic(),
		"availability_topic":    p.cfg.MQTTAvailabilityTopic,
		"payload_available":     p.cfg.MQTTAvailabilityOn,
		"payload_not_available": p.cfg.MQTTAvailabilityOff,
		"value_template":        `{{ value_json.user }}`,
		"icon":                  "mdi:account",

		"device": map[string]any{
			"identifiers":  []string{"sia2mqtt_ajax"},
			"name":         "sia2mqtt Ajax",
			"manufacturer": "Custom",
			"model":        "SIA DC-09 Receiver",
		},
	}

	userBody, _ := json.Marshal(userPayload)
	userTopic := p.userDiscoveryConfigTopic()
	t2 := p.client.Publish(userTopic, p.cfg.MQTTQOS, true, userBody)
	t2.Wait()
	if t2.Error() == nil {
		log.Printf("[%s] MQTT discovery (user) published: %s\n", time.Now().Format("15:04:05"), userTopic)
		p.discoverySent.Store(true)
	} else {
		log.Printf("[%s] MQTT discovery (user) publish error: %v\n", time.Now().Format("15:04:05"), t2.Error())
	}
}

func (p *Publisher) Connect() error {
	opts := mqtt.NewClientOptions()
	opts.AddBroker(p.cfg.MQTTBroker)

	clientID := p.cfg.MQTTClientID
	if clientID == "" {
		clientID = fmt.Sprintf("sia2mqtt-%d", time.Now().UnixNano())
	}
	opts.SetClientID(clientID)

	if p.cfg.MQTTUser != "" {
		opts.SetUsername(p.cfg.MQTTUser)
		opts.SetPassword(p.cfg.MQTTPass)
	}

	opts.SetAutoReconnect(true)
	opts.SetConnectRetry(true)
	opts.SetConnectRetryInterval(3 * time.Second)
	opts.SetKeepAlive(30 * time.Second)
	opts.SetPingTimeout(10 * time.Second)

	if strings.HasPrefix(strings.ToLower(p.cfg.MQTTBroker), "tls://") || strings.HasPrefix(strings.ToLower(p.cfg.MQTTBroker), "ssl://") {
		tlsCfg := &tls.Config{InsecureSkipVerify: p.cfg.MQTTInsecureSkipVerify}
		opts.SetTLSConfig(tlsCfg)
	}

	if p.cfg.MQTTAvailabilityTopic != "" {
		opts.SetWill(p.cfg.MQTTAvailabilityTopic, p.cfg.MQTTAvailabilityOff, p.cfg.MQTTQOS, true)
	}

	opts.OnConnect = func(c mqtt.Client) {
		if p.cfg.MQTTAvailabilityTopic != "" {
			t := c.Publish(p.cfg.MQTTAvailabilityTopic, p.cfg.MQTTQOS, true, p.cfg.MQTTAvailabilityOn)
			t.Wait()
		}
		// Publish discovery config on (re)connect
		p.publishDiscoveryConfig()
	}

	opts.OnConnectionLost = func(_ mqtt.Client, err error) {
		log.Printf("[%s] MQTT connection lost: %v\n", time.Now().Format("15:04:05"), err)
		p.discoverySent.Store(false)
	}

	p.client = mqtt.NewClient(opts)
	tok := p.client.Connect()
	tok.Wait()
	if err := tok.Error(); err != nil {
		return err
	}

	log.Printf("[%s] MQTT connected as %s to %s\n", time.Now().Format("15:04:05"), clientID, p.cfg.MQTTBroker)
	// Ensure discovery is published even if OnConnect already fired
	p.publishDiscoveryConfig()
	return nil
}

func (p *Publisher) IsConnected() bool {
	return p.client != nil && p.client.IsConnected()
}

// Publishes JSON to mqtt_topic:
// {"state":"armed","code":"CL","ts":"2026-01-30T22:22:14+01:00"}
func (p *Publisher) PublishState(state AlarmState, code string) {
	p.mu.Lock()
	defer p.mu.Unlock()

	if state == p.lastState && code == p.lastCode {
		return
	}
	p.lastState = state
	p.lastCode = code

	if p.client == nil || !p.client.IsConnected() {
		log.Printf("[%s] MQTT not connected; dropping publish state=%s code=%s\n", time.Now().Format("15:04:05"), state, code)
		p.stats.UpdateMQTTPublish(false)
		return
	}

	msg := map[string]any{
		"state": string(state),
		"code":  code,
		"ts":    time.Now().Format(time.RFC3339),
	}
	body, _ := json.Marshal(msg)

	t := p.client.Publish(p.cfg.MQTTTopic, p.cfg.MQTTQOS, p.cfg.MQTTRetain, body)
	t.Wait()
	if err := t.Error(); err != nil {
		log.Printf("[%s] MQTT publish error: %v\n", time.Now().Format("15:04:05"), err)
		p.stats.UpdateMQTTPublish(false)
		return
	}

	log.Printf("[%s] MQTT publish: topic=%s payload=%s\n", time.Now().Format("15:04:05"), p.cfg.MQTTTopic, string(body))
	p.stats.UpdateMQTTPublish(true)
}

// Publishes user ID to separate topic:
// {"user":"502","ts":"2026-01-30T22:22:14+01:00"}
func (p *Publisher) PublishUser(userID string) {
	p.mu.Lock()
	defer p.mu.Unlock()

	if userID == p.lastUser {
		return
	}
	p.lastUser = userID

	if p.client == nil || !p.client.IsConnected() {
		log.Printf("[%s] MQTT not connected; dropping publish user=%s\n", time.Now().Format("15:04:05"), userID)
		return
	}

	msg := map[string]any{
		"user": userID,
		"ts":   time.Now().Format(time.RFC3339),
	}
	body, _ := json.Marshal(msg)

	userTopic := p.userTopic()
	t := p.client.Publish(userTopic, p.cfg.MQTTQOS, p.cfg.MQTTRetain, body)
	t.Wait()
	if err := t.Error(); err != nil {
		log.Printf("[%s] MQTT user publish error: %v\n", time.Now().Format("15:04:05"), err)
		return
	}

	if p.cfg.Verbose {
		log.Printf("[%s] MQTT user publish: topic=%s payload=%s\n", time.Now().Format("15:04:05"), userTopic, string(body))
	}
}

// =====================
// HTTP stats server
// =====================

func startHTTP(cfg Config, pub *Publisher, stats *RuntimeStats) {
	mux := http.NewServeMux()

	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})

	mux.HandleFunc("/state", func(w http.ResponseWriter, _ *http.Request) {
		stats.mu.RLock()
		lastState := stats.LastState
		lastCode := stats.LastCode
		lastUser := stats.LastUser
		lastEventTime := stats.LastEventTime
		stats.mu.RUnlock()

		out := map[string]any{
			"state":           lastState,
			"code":            lastCode,
			"user":            lastUser,
			"last_event_time": zeroOrRFC3339(lastEventTime),
		}

		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(out)
	})

	mux.HandleFunc("/stats", func(w http.ResponseWriter, _ *http.Request) {
		uptime := time.Since(stats.StartTime)

		stats.mu.RLock()
		lastState := stats.LastState
		lastCode := stats.LastCode
		lastUser := stats.LastUser
		lastRaw := stats.LastEventRaw
		lastEventTime := stats.LastEventTime
		lastMQTTPubTime := stats.LastMQTTPublishTime
		stats.mu.RUnlock()

		out := map[string]any{
			"uptime_seconds": int64(uptime.Seconds()),
			"start_time":     stats.StartTime.Format(time.RFC3339),

			"active_connections": atomic.LoadInt64(&stats.ActiveConn),

			"frames_rx":                 atomic.LoadUint64(&stats.FramesRx),
			"acks_tx":                   atomic.LoadUint64(&stats.AcksTx),
			"rejected_account_mismatch": atomic.LoadUint64(&stats.RejectedAccountMismatch),

			"mqtt_connected": pub.IsConnected(),
			"mqtt_pub_ok":    atomic.LoadUint64(&stats.MQTTPubOK),
			"mqtt_pub_err":   atomic.LoadUint64(&stats.MQTTPubErr),

			"last_state":         lastState,
			"last_code":          lastCode,
			"last_user":          lastUser,
			"last_event_time":    zeroOrRFC3339(lastEventTime),
			"last_mqtt_pub_time": zeroOrRFC3339(lastMQTTPubTime),
			"last_event_raw":     lastRaw,

			"ha_discovery_state_topic": pub.discoveryConfigTopic(),
			"ha_discovery_user_topic":  pub.userDiscoveryConfigTopic(),
			"ha_unique_id":             pub.uniqueID(),
		}

		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(out)
	})

	srv := &http.Server{
		Addr:              cfg.HTTPListenAddr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	go func() {
		log.Printf("[%s] HTTP stats listening on http://%s (endpoints: /health, /state, /stats)\n",
			time.Now().Format("15:04:05"), cfg.HTTPListenAddr)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Printf("[%s] HTTP server error: %v\n", time.Now().Format("15:04:05"), err)
		}
	}()
}

func zeroOrRFC3339(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return t.Format(time.RFC3339)
}

func loadPersistedState(path string, stats *RuntimeStats) error {
	if path == "" {
		return nil
	}
	body, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	var p PersistedState
	if err := json.Unmarshal(body, &p); err != nil {
		return err
	}
	stats.ApplyPersistedState(p)
	return nil
}

func persistState(path string, stats *RuntimeStats) error {
	if path == "" {
		return nil
	}
	state := stats.Snapshot()
	if state.State == "" {
		return nil
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, "state-*.json")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	_, writeErr := tmp.Write(append(body, '\n'))
	closeErr := tmp.Close()
	if writeErr != nil {
		_ = os.Remove(tmpName)
		return writeErr
	}
	if closeErr != nil {
		_ = os.Remove(tmpName)
		return closeErr
	}
	if err := os.Rename(tmpName, path); err != nil {
		_ = os.Remove(tmpName)
		return err
	}
	return nil
}

// =====================
// Main SIA server
// =====================

func handleConnection(conn net.Conn, cfg Config, pub *Publisher, stats *RuntimeStats) {
	defer conn.Close()

	atomic.AddInt64(&stats.ActiveConn, 1)
	defer atomic.AddInt64(&stats.ActiveConn, -1)

	ra := conn.RemoteAddr().String()
	log.Printf("[%s] CONNECT %s\n", time.Now().Format("15:04:05"), ra)

	r := bufio.NewReaderSize(conn, 64*1024)

	for {
		_ = conn.SetReadDeadline(time.Now().Add(60 * time.Second))

		frame, err := readFrame(r)
		if err != nil {
			if ne, ok := err.(net.Error); ok && ne.Timeout() {
				continue
			}
			log.Printf("[%s] DISCONNECT %s err=%v\n", time.Now().Format("15:04:05"), ra, err)
			return
		}
		if len(frame) == 0 {
			continue
		}

		atomic.AddUint64(&stats.FramesRx, 1)

		raw := string(frame)
		log.Printf("\n[%s] RECV %s: %s\n", time.Now().Format("15:04:05"), ra, raw)
		if cfg.Verbose {
			log.Printf("[%s] RECV_HEX: %s\n", time.Now().Format("15:04:05"), hex.EncodeToString(frame))
		}

		mh := reHeader.FindStringSubmatch(raw)
		if len(mh) >= 5 {
			seq := mh[1]
			rcvrOpt := mh[2]
			lpref := mh[3]
			acct := mh[4]

			// VERIFY ACCOUNT ID
			if cfg.SIAAccountID != "" && acct != cfg.SIAAccountID {
				atomic.AddUint64(&stats.RejectedAccountMismatch, 1)
				log.Printf("[%s] SECURITY: Rejected frame from account '%s' (expected '%s') from %s\n",
					time.Now().Format("15:04:05"), acct, cfg.SIAAccountID, ra)
				// Don't send ACK for invalid accounts
				continue
			}

			if cfg.Verbose && cfg.SIAAccountID != "" {
				log.Printf("[%s] VERIFIED: account=%s\n", time.Now().Format("15:04:05"), acct)
			}

			ack := buildAck(seq, rcvrOpt, lpref, acct)
			_, _ = conn.Write(ack)
			atomic.AddUint64(&stats.AcksTx, 1)

			if cfg.Verbose {
				log.Printf("[%s] SENT: %s\n", time.Now().Format("15:04:05"), strings.TrimSpace(string(ack)))
			}
		} else {
			log.Println("DEBUG: frame did not match DC-09 header; skipping ACK + parsing")
			continue
		}

		// Parse event code and user ID
		me := reEventCode.FindStringSubmatch(raw)
		if len(me) >= 2 {
			eventCode := me[1] // "OP", "CL", etc.
			userID := ""
			if len(me) > 2 {
				userID = me[2] // "502", "123", etc.
			}

			if st, ok := codeToState[eventCode]; ok {
				log.Printf("[%s] STATUS: %s (code=%s, user=%s)\n",
					time.Now().Format("15:04:05"), st, eventCode, userID)
				stats.UpdateEvent(st, eventCode, userID, raw)
				if err := persistState(cfg.StateFile, stats); err != nil {
					log.Printf("[%s] WARN: failed to persist state: %v\n", time.Now().Format("15:04:05"), err)
				}
				pub.PublishState(st, eventCode)
				if userID != "" {
					pub.PublishUser(userID)
				}
			} else if cfg.Verbose {
				log.Printf("[%s] INFO: unhandled event code: %s (user=%s)\n",
					time.Now().Format("15:04:05"), eventCode, userID)
			}
		}
	}
}

func main() {
	cfgPath := DefaultConfigPath
	if len(os.Args) >= 2 && strings.TrimSpace(os.Args[1]) != "" {
		cfgPath = os.Args[1]
	}

	cfg, err := loadConfig(cfgPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "config error: %v\n", err)
		os.Exit(2)
	}

	// Setup logging - if log_file is configured, use it; otherwise disable logging
	if cfg.LogFile != "" {
		logDir := filepath.Dir(cfg.LogFile)
		if err := os.MkdirAll(logDir, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "failed to create log directory: %v\n", err)
			os.Exit(2)
		}

		logger := &lumberjack.Logger{
			Filename:   cfg.LogFile,
			MaxSize:    cfg.LogMaxSizeMB,
			MaxBackups: cfg.LogMaxBackups,
			MaxAge:     cfg.LogMaxAgeDays,
			Compress:   true,
		}

		log.SetOutput(logger)
		log.SetFlags(0) // We add our own timestamps

		log.Printf("[%s] sia2mqtt starting - logging to %s (max_size=%dMB, max_backups=%d, max_age=%dd)\n",
			time.Now().Format("15:04:05"), cfg.LogFile, cfg.LogMaxSizeMB, cfg.LogMaxBackups, cfg.LogMaxAgeDays)
	} else {
		// No log file configured - disable logging by sending to /dev/null
		log.SetOutput(io.Discard)
	}

	stats := &RuntimeStats{
		StartTime: time.Now(),
		LastState: StateUnknown,
	}

	if err := loadPersistedState(cfg.StateFile, stats); err != nil {
		log.Printf("[%s] WARN: failed to load persisted state: %v\n", time.Now().Format("15:04:05"), err)
	}

	log.Printf("[%s] Config: listen=%s account=%s http=%s mqtt_broker=%s mqtt_topic=%s qos=%d retain=%v discovery=%v\n",
		time.Now().Format("15:04:05"), cfg.SIAListenAddr, cfg.SIAAccountID, cfg.HTTPListenAddr,
		cfg.MQTTBroker, cfg.MQTTTopic, cfg.MQTTQOS, cfg.MQTTRetain, cfg.MQTTDiscoveryEnable)

	pub := &Publisher{cfg: cfg, stats: stats}
	if err := pub.Connect(); err != nil {
		log.Fatalf("[%s] mqtt connect error: %v\n", time.Now().Format("15:04:05"), err)
	}

	startHTTP(cfg, pub, stats)

	l, err := net.Listen("tcp", cfg.SIAListenAddr)
	if err != nil {
		log.Fatalf("[%s] listen error: %v\n", time.Now().Format("15:04:05"), err)
	}
	defer l.Close()

	log.Printf("[%s] SIA server listening on %s\n", time.Now().Format("15:04:05"), cfg.SIAListenAddr)

	for {
		c, err := l.Accept()
		if err != nil {
			log.Printf("[%s] accept error: %v\n", time.Now().Format("15:04:05"), err)
			continue
		}
		go handleConnection(c, cfg, pub, stats)
	}
}
